name: Compile Test

on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Build Tools
              run: |
                  sudo apt-get update
                  sudo apt install build-essential
            - name: Build App
              run: |
                  mkdir bin
                  g++ $(find . -type f -iregex ".*\.cpp") -O2 -o ./bin/honeycomb -std=c++20
            - name: Test App Binary File Exists
              run: |
                  test -e ./bin/honeycomb
